server:
  port: 8085
spring:
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment: #配置rabbimq连接环境
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: eric
                password: 123456
                virtual-host: /
      bindings:
        output:
          destination: MyOutput  #exchange名称，交换模式默认是topic
          content-type: application/json
        input:
          destination: MyInput
          content-type: application/json